name: eWrangler
favicon: null
layout_spectrum: 0.15228
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3f423d'
    - '#9a7a51'
    - '#000000'
    - '#fffdfb'
    - '#bec0ae'
  brandStrength: 0.1875
  lightness: 0.4108718882780522
  saturation: 0.9186880351044238
  rhythmicContrast: 0.02004600432701409
purpose: []
