name: eWrangler
favicon: null
layout_spectrum: 0.15228
typography_spectrum: 0.5380171970464289
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5313077920582145
  lightness: 0.4108718882780522
  saturation: 0.9186880351044238
  rhythmicContrast: 0.02004600432701409
purpose: []
